"""Look at what law search returns (task 2.8).

    python -m haqqi.rag.probe "my salary is unpaid"        # top 8 for one query
    python -m haqqi.rag.probe --all     # the 10 probe queries → eval/retrieval_probe_<EMBEDDER>.md

Search only: no Law Pack top-up, so the result shows what retrieval finds on its own.
"""

import argparse
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import psycopg

from haqqi.config import get_settings
from haqqi.rag.embed import Embedder, get_embedder
from haqqi.rag.lawdata import LawPack
from haqqi.rag.retrieve import RetrievedChunk, retrieve

EVAL_DIR = Path(__file__).resolve().parents[3] / "eval"
NO_PACK = LawPack(topics={}, related={}, always=[])
HIT_AT = 5


@dataclass(frozen=True)
class ProbeQuery:
    lang: str
    text: str
    expected: str  # article prefix, e.g. "fdl33-2021:art51"


QUERIES = [
    ProbeQuery("en", "My salary has not been paid for three months", "fdl33-2021:art22"),
    ProbeQuery("en", "How is my end of service gratuity calculated?", "fdl33-2021:art51"),
    ProbeQuery("en", "I was terminated the same day without any notice period", "fdl33-2021:art43"),
    ProbeQuery("en", "My employer is keeping my passport", "fdl33-2021:art13"),
    ProbeQuery("en", "How many days of annual leave am I entitled to?", "fdl33-2021:art29"),
    ProbeQuery("hi", "मेरी तनख्वाह तीन महीने से नहीं मिली है", "fdl33-2021:art22"),
    ProbeQuery("hi", "नौकरी छोड़ने पर ग्रेच्युटी कैसे गिनी जाती है?", "fdl33-2021:art51"),
    ProbeQuery("ar", "لم أستلم راتبي منذ ثلاثة أشهر", "fdl33-2021:art22"),
    ProbeQuery("ar", "كيف تحسب مكافأة نهاية الخدمة؟", "fdl33-2021:art51"),
    ProbeQuery("ar", "أجر ساعات العمل الإضافية", "fdl33-2021:art19"),
]


def search(conn: psycopg.Connection, embedder: Embedder, query: str) -> list[RetrievedChunk]:
    return retrieve(conn, query, embedder, NO_PACK)


def rank_of(results: list[RetrievedChunk], expected: str) -> int | None:
    for rank, chunk in enumerate(results, start=1):
        if chunk.id == expected or chunk.id.startswith(expected + ":"):
            return rank
    return None


def report(rows: list[tuple[ProbeQuery, list[RetrievedChunk]]], embedder_name: str) -> str:
    hits = sum(1 for q, res in rows if (r := rank_of(res, q.expected)) and r <= HIT_AT)
    lines = [
        "# Retrieval probe (task 2.8)",
        "",
        f"Generated by `python -m haqqi.rag.probe --all` on {date.today()} with "
        f"`EMBEDDER={embedder_name}`. Search only (no Law Pack top-up).",
        "",
        f"**Expected article in the top {HIT_AT}: {hits}/{len(rows)}**",
        "",
        "| # | Lang | Query | Expected | Rank | Top 5 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for i, (q, res) in enumerate(rows, start=1):
        rank = rank_of(res, q.expected)
        top = ", ".join(c.id.removeprefix("fdl33-2021:") for c in res[:HIT_AT])
        lines.append(
            f"| {i} | {q.lang} | {q.text} | {q.expected.split(':')[-1]} | {rank or '–'} | {top} |"
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("query", nargs="?")
    parser.add_argument("--all", action="store_true", help="run the probe set, write a report")
    args = parser.parse_args(argv)
    settings = get_settings()
    if not settings.database_url or not (args.query or args.all):
        parser.error("needs DATABASE_URL and a query (or --all)")
    embedder = get_embedder(settings)
    with psycopg.connect(settings.database_url) as conn:
        if args.all:
            rows = [(q, search(conn, embedder, q.text)) for q in QUERIES]
            out = EVAL_DIR / f"retrieval_probe_{settings.embedder}.md"
            out.write_text(report(rows, settings.embedder), encoding="utf-8")
            print(out.read_text(encoding="utf-8"))
        else:
            for rank, c in enumerate(search(conn, embedder, args.query), start=1):
                print(f"{rank}. {c.id}  {c.title}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
